name: Set MIME Type for CSS

on:
  push:
    paths:
      - '**.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set MIME type
        run: |
          find . -name '*.css' -exec git add --chmod=+x {} \;
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git commit -m "Set MIME type for CSS files" -a
          git push
